import { Link } from 'wouter';
import { ArrowRight, ExternalLink, Music, ShoppingBag } from 'lucide-react';
import { CLARITY_WEBSITE_EDITION, CLARITY_WEBSITE_EDITION_TRACKS, type ClarityWebsiteTrack } from '@/data/clarity-website-edition';

const story = 'Twelve core songs recorded across 2024–2025, largely at Mount Pisgah Baptist Church on Chicago’s South Side. CLARITY closes a post-COVID mixtape era: first titled Dominion, then becoming Clarity in hindsight. It moves through confusion, surrender, discipline and purpose, with the Black Metropolis of Bronzeville as its central image.';
const albumTracks = CLARITY_WEBSITE_EDITION_TRACKS.slice(0, 12);
const websiteExclusive = CLARITY_WEBSITE_EDITION_TRACKS.slice(12);

function RecordTracks({ tracks }: { tracks: ClarityWebsiteTrack[] }) {
  return <>{tracks.map((track) => <div key={track.id} className="flex items-center gap-4 rounded px-3 py-3 transition-colors hover:bg-emerald-900/15"><span className="w-7 text-right font-mono text-xs text-amber-600/80">{track.id.toString().padStart(2, '0')}</span><div className="min-w-0 flex-1"><div className="flex min-w-0 items-center gap-2"><p className="truncate text-sm text-emerald-50">{track.title}</p>{track.isWebsiteExclusive && <span className="shrink-0 rounded border border-amber-300/35 px-1.5 py-0.5 text-[8px] uppercase tracking-[0.14em] text-amber-200">Website Exclusive</span>}</div><p className="hidden truncate text-xs text-emerald-300/65 sm:block">{track.description}</p></div><span className="font-mono text-xs text-emerald-400/70">{track.duration}</span></div>)}</>;
}

export default function ClaritySales() {
  return (
    <main className="min-h-screen text-white" style={{ fontFamily: "'DM Mono', monospace", background: 'linear-gradient(to bottom, #071c14, #103d2d, #090b09)' }}>
      <header className="sticky top-0 z-40 border-b border-emerald-900/35 bg-black/80 px-4 py-4 backdrop-blur-md"><div className="mx-auto flex max-w-5xl items-center justify-between"><Link href="/" className="font-mono text-xs uppercase tracking-widest text-emerald-300 transition-colors hover:text-emerald-100">← Home</Link><span className="font-mono text-xs uppercase tracking-[0.3em] text-emerald-400">Moses</span><Link href="/store" className="font-mono text-xs uppercase tracking-widest text-zinc-400 transition-colors hover:text-zinc-200">Store</Link></div></header>

      <section className="relative px-4 pb-20 pt-16 sm:pb-28 sm:pt-24"><div className="pointer-events-none absolute inset-0 overflow-hidden"><div className="absolute left-1/3 top-1/3 h-[500px] w-[500px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-emerald-700/20 blur-3xl" /><div className="absolute bottom-1/4 right-1/4 h-[300px] w-[300px] rounded-full bg-amber-700/10 blur-3xl" /></div><div className="relative z-10 mx-auto grid max-w-5xl items-center gap-10 md:grid-cols-2 md:gap-16"><div className="order-2 flex justify-center md:order-1 md:justify-start"><div className="relative"><div className="absolute inset-0 rounded-lg bg-emerald-700/20 blur-2xl" /><img src={CLARITY_WEBSITE_EDITION.cover} alt="CLARITY Website Edition cover" className="relative h-72 w-72 rounded-lg object-cover shadow-2xl sm:h-80 sm:w-80 md:h-96 md:w-96" /></div></div><div className="order-1 text-center md:order-2 md:text-left"><p className="mb-5 inline-block rounded-full border border-emerald-600/70 px-4 py-1.5 font-mono text-xs uppercase tracking-[0.2em] text-emerald-200">Album · 13 tracks · Website Edition</p><h1 className="mb-3 font-bebas text-[clamp(3rem,10vw,8rem)] leading-none tracking-wide text-emerald-50">CLARITY</h1><p className="mb-8 font-cormorant text-2xl italic text-amber-300/85">MOSES</p><div className="mb-8 flex flex-wrap justify-center gap-4 text-xs font-mono uppercase tracking-widest text-emerald-300/75 md:justify-start"><span>13 tracks</span><span className="text-emerald-700">·</span><span>{CLARITY_WEBSITE_EDITION.runtime}</span><span className="text-emerald-700">·</span><span>{CLARITY_WEBSITE_EDITION.year}</span></div><div className="flex flex-col justify-center gap-3 sm:flex-row md:justify-start"><Link href="/listen" className="flex items-center justify-center gap-2 rounded-lg bg-emerald-700 px-6 py-3 font-bebas text-lg tracking-wide text-white transition-colors hover:bg-emerald-600">Listen Now <Music className="h-4 w-4" /></Link><Link href="/checkout?product=clarity" className="flex items-center justify-center gap-2 rounded-lg border border-amber-500/60 px-6 py-3 font-bebas text-lg tracking-wide text-amber-200 transition-colors hover:border-amber-300 hover:text-amber-100">Own It — $12 <ShoppingBag className="h-4 w-4" /></Link></div></div></div></section>

      <section className="border-y border-emerald-900/30 px-4 py-16 sm:py-20"><div className="mx-auto grid max-w-5xl gap-10 md:grid-cols-[0.7fr_1.3fr] md:items-start"><div><p className="font-mono text-xs uppercase tracking-[0.25em] text-amber-300/75">The Story</p><h2 className="mt-4 font-bebas text-5xl tracking-wide text-emerald-50">WHAT BECAME CLEAR.</h2></div><div><p className="font-cormorant text-2xl leading-relaxed text-emerald-50/85">{story}</p><p className="mt-5 text-sm leading-7 text-emerald-200/70">The Website Edition comes directly from Moses and includes the exclusive track.</p></div></div></section>

      <section className="px-4 py-16 sm:py-20"><div className="mx-auto max-w-3xl"><div className="mb-8 flex items-end justify-between gap-4"><div><p className="font-mono text-xs uppercase tracking-[0.25em] text-amber-300/75">Record back</p><h2 className="mt-2 font-bebas text-4xl tracking-wide text-emerald-100">TRACKLIST</h2></div><span className="font-mono text-xs uppercase tracking-widest text-emerald-400/70">13 tracks · {CLARITY_WEBSITE_EDITION.runtime}</span></div><div className="rounded-lg border border-emerald-900/40 bg-black/20 p-3"><p className="px-3 pb-2 pt-1 font-mono text-[10px] uppercase tracking-[0.24em] text-amber-300/80">The Album</p><div className="space-y-1"><RecordTracks tracks={albumTracks} /></div><div className="mx-3 my-4 border-t border-emerald-900/40" /><p className="px-3 pb-2 font-mono text-[10px] uppercase tracking-[0.24em] text-emerald-300/75">Website Exclusive</p><div className="space-y-1"><RecordTracks tracks={websiteExclusive} /></div></div><div className="mt-10 flex flex-col justify-center gap-4 sm:flex-row"><Link href="/listen" className="inline-flex items-center justify-center gap-2 rounded-lg bg-emerald-700 px-8 py-4 font-bebas text-lg tracking-wide text-white transition-colors hover:bg-emerald-600">Start Listening <ArrowRight className="h-5 w-5" /></Link><Link href="/checkout?product=clarity" className="inline-flex items-center justify-center gap-2 rounded-lg border border-amber-500/55 px-8 py-4 font-bebas text-lg tracking-wide text-amber-200/90 transition-colors hover:border-amber-300 hover:text-amber-100">Own It — $12 <ShoppingBag className="h-5 w-5" /></Link></div></div></section>

      <section className="border-y border-emerald-900/30 px-4 py-16 sm:py-20"><div className="mx-auto grid max-w-5xl gap-10 md:grid-cols-2"><div><p className="font-mono text-xs uppercase tracking-[0.25em] text-amber-300/75">Credits</p><p className="mt-4 text-sm leading-7 text-emerald-50/85">Written and performed by Moses. Recorded at Mount Pisgah Baptist Church, Chicago.<br /><br />Production: [PRODUCTION CREDITS]</p></div><div><p className="font-mono text-xs uppercase tracking-[0.25em] text-amber-300/75">Also On</p><div className="mt-4 space-y-3"><a href="https://mosessog.bandcamp.com/album/clarity-2" target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-lg border border-emerald-900/50 px-4 py-3 text-sm text-emerald-100 transition hover:border-emerald-400"><span>Bandcamp</span><ExternalLink className="h-4 w-4" /></a><a href="https://soundcloud.com/mosessog/sets/clarity-1?si=16f0f5af5c5041be915be8599d18afe7&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing" target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-lg border border-emerald-900/50 px-4 py-3 text-sm text-emerald-100 transition hover:border-emerald-400"><span>SoundCloud</span><ExternalLink className="h-4 w-4" /></a><a href="https://distrokid.com/hyperfollow/mosesofelgin/clarity-2" target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-lg border border-emerald-900/50 px-4 py-3 text-sm text-emerald-100 transition hover:border-emerald-400"><span>Streaming Edition · Spotify Pre-Save</span><ExternalLink className="h-4 w-4" /></a><a href="https://www.youtube.com/playlist?list=PLTt1W4MaPgT3799Kyqr9oAV62pPsOAxS0" target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-lg border border-emerald-900/50 px-4 py-3 text-sm text-emerald-100 transition hover:border-emerald-400"><span>YouTube Playlist</span><ExternalLink className="h-4 w-4" /></a><p className="rounded-lg border border-amber-300/15 bg-amber-300/5 px-4 py-3 text-xs leading-5 text-amber-100/75">Streaming edition: 12 tracks. Wish I Had You is exclusive to this site.</p></div></div></div></section>

      <footer className="border-t border-emerald-900/30 px-4 py-10 text-center text-emerald-500/70"><p className="text-sm">© 2026 MOSES SOG. All rights reserved.</p></footer>
    </main>
  );
}
