import { ArrowRight, Instagram, LibraryBig, Mail, MicVocal, Play, ShoppingBag, Twitch, Twitter, Youtube } from 'lucide-react';
import { Link } from 'wouter';
import { CLARITY_COVER } from '@/data/project-catalog';

const pathways = [
  { href: '/clarity-sales', eyebrow: 'Flagship project', title: 'BUY CLARITY', copy: 'Twelve tracks. Direct purchase. Secure checkout.', icon: ShoppingBag, primary: true },
  { href: '/listen', eyebrow: 'Listen first', title: 'UNLOCK THE ALBUM', copy: 'Enter email, then hear the full CLARITY journey.', icon: Play },
  { href: '/projects', eyebrow: 'The vault', title: 'EXPLORE THE ARCHIVE', copy: 'Six projects and a deeper catalog of recordings.', icon: LibraryBig },
  { href: '/artist', eyebrow: 'Professional pathway', title: 'ARTIST / EPK', copy: 'Videos, booking information, and press materials.', icon: MicVocal },
  { href: '/connect', eyebrow: 'Direct line', title: 'CONNECT', copy: 'Booking, partnership, media, and community.', icon: Mail },
];

export default function Event() {
  return (
    <main className="min-h-screen bg-[radial-gradient(circle_at_70%_0%,rgba(184,134,11,0.16),transparent_22%),#090909] text-zinc-100">
      <header className="border-b border-amber-100/10 bg-zinc-950/85 px-4 py-4 backdrop-blur-xl"><div className="mx-auto flex max-w-md items-center justify-between"><p className="font-display text-xl tracking-[0.16em] text-zinc-100">MOSES SOG</p><p className="text-[10px] uppercase tracking-[0.22em] text-amber-200">The Vault</p></div></header>
      <section className="px-4 pb-10 pt-12"><div className="mx-auto max-w-md text-center"><div className="mx-auto overflow-hidden rounded-2xl border border-amber-100/20 bg-zinc-900 p-1 shadow-2xl"><img src={CLARITY_COVER} alt="CLARITY album cover" className="aspect-square w-full rounded-xl object-cover" /></div><p className="mt-8 text-[10px] uppercase tracking-[0.28em] text-amber-200">Chicago · Music · Mission</p><h1 className="mt-4 font-display text-5xl leading-[0.82] tracking-[0.1em] text-zinc-50">WELCOME TO THE WORK.</h1><p className="mt-5 font-serif text-2xl italic leading-snug text-amber-50/80">Scan complete. Choose your doorway.</p></div></section>
      <section className="px-4 pb-10"><div className="mx-auto max-w-md space-y-3">{pathways.map(({ href, eyebrow, title, copy, icon: Icon, primary }) => <Link key={href} href={href} className={`group block rounded-2xl border p-5 transition focus:outline-none focus-visible:ring-2 focus-visible:ring-amber-300 ${primary ? 'border-amber-200/50 bg-amber-300 text-zinc-950 hover:bg-amber-200' : 'border-amber-100/12 bg-zinc-950/80 hover:-translate-y-0.5 hover:border-amber-200/40'}`}><div className="flex items-start gap-4"><div className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border ${primary ? 'border-zinc-950/20 bg-zinc-950/10' : 'border-amber-100/15 bg-amber-300/10 text-amber-200'}`}><Icon className="h-5 w-5" aria-hidden="true" /></div><div className="min-w-0 flex-1 text-left"><p className={`text-[9px] uppercase tracking-[0.2em] ${primary ? 'text-zinc-950/65' : 'text-amber-200'}`}>{eyebrow}</p><h2 className={`mt-1 font-display text-2xl tracking-[0.12em] ${primary ? 'text-zinc-950' : 'text-zinc-100'}`}>{title}</h2><p className={`mt-2 text-xs leading-5 ${primary ? 'text-zinc-950/75' : 'text-zinc-500'}`}>{copy}</p></div><ArrowRight className={`mt-3 h-4 w-4 shrink-0 transition group-hover:translate-x-1 ${primary ? 'text-zinc-950' : 'text-amber-200'}`} aria-hidden="true" /></div></Link>)}</div></section>
      <footer className="border-t border-amber-100/10 bg-[#100d09] px-4 py-8"><div className="mx-auto max-w-md"><p className="text-center text-[10px] uppercase tracking-[0.2em] text-zinc-600">Follow the work</p><div className="mt-4 flex justify-center gap-3">{[[Instagram,'Instagram','https://instagram.com/moses_sog'],[Youtube,'YouTube','https://youtube.com/@MosesSOG'],[Twitch,'Twitch','https://twitch.tv/mosessog'],[Twitter,'Twitter / X','https://twitter.com/sogmoses']].map(([Icon,label,href]) => <a key={String(label)} href={String(href)} target="_blank" rel="noopener noreferrer" aria-label={String(label)} className="flex h-11 w-11 items-center justify-center rounded-xl border border-amber-100/12 text-amber-200 transition hover:border-amber-200/50 hover:bg-amber-200/5"><Icon className="h-4 w-4" aria-hidden="true" /></a>)}</div><p className="mt-5 text-center text-[10px] uppercase tracking-[0.18em] text-zinc-600">@moses_sog · Direct from MOSES</p></div></footer>
    </main>
  );
}
