import { Link } from 'wouter';
import { ArrowRight, ExternalLink, Music, ShoppingBag } from 'lucide-react';
import { NEW_GENESIS_COVER, NEW_GENESIS_TRACKS, NEW_GENESIS_META, type NewGenesisTrack } from '../data/new-genesis-bundle';

const story = 'New Genesis is the debut project from Moses, seven years in the making and recorded in the basement of Mount Pisgah Baptist Church on Chicago\'s South Side. It traces his growth as an artist and his spiritual transformation since being baptized at 20, opening on a five-song walk through Genesis, Exodus, Leviticus, Numbers and Deuteronomy.';
const fiveBooks = NEW_GENESIS_TRACKS.slice(0, 5);
const remainingTracks = NEW_GENESIS_TRACKS.slice(5);

function RecordTracks({ tracks }: { tracks: NewGenesisTrack[] }) {
  return <>{tracks.map((track) => <div key={track.id} className="flex items-center gap-4 rounded px-3 py-3 transition-colors hover:bg-indigo-900/15"><span className="w-7 text-right font-mono text-xs text-yellow-700/70">{track.id.toString().padStart(2, '0')}</span><div className="min-w-0 flex-1"><p className="truncate text-sm text-indigo-100">{track.title}</p><p className="hidden truncate text-xs text-indigo-500/70 sm:block">{track.description}</p></div><span className="font-mono text-xs text-indigo-600">{track.duration}</span></div>)}</>;
}

export default function NewGenesis() {
  return (
    <main className="min-h-screen text-white" style={{ fontFamily: "'DM Mono', monospace", background: 'linear-gradient(to bottom, #0f0c29, #1a1040, #0d0d0d)' }}>
      <header className="sticky top-0 z-40 border-b border-indigo-900/30 bg-black/80 px-4 py-4 backdrop-blur-md"><div className="mx-auto flex max-w-5xl items-center justify-between"><Link href="/music" className="font-mono text-xs uppercase tracking-widest text-indigo-400 transition-colors hover:text-indigo-200">← All Music</Link><span className="font-mono text-xs uppercase tracking-[0.3em] text-indigo-500">Moses</span><Link href="/store" className="font-mono text-xs uppercase tracking-widest text-zinc-500 transition-colors hover:text-zinc-300">Store</Link></div></header>

      <section className="relative px-4 pb-20 pt-16 sm:pb-28 sm:pt-24"><div className="pointer-events-none absolute inset-0 overflow-hidden"><div className="absolute left-1/3 top-1/3 h-[500px] w-[500px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-indigo-900/20 blur-3xl" /><div className="absolute bottom-1/4 right-1/4 h-[300px] w-[300px] rounded-full bg-yellow-900/10 blur-3xl" /></div><div className="relative z-10 mx-auto grid max-w-5xl items-center gap-10 md:grid-cols-2 md:gap-16"><div className="order-2 flex justify-center md:order-1 md:justify-start"><div className="relative"><div className="absolute inset-0 rounded-lg bg-indigo-700/20 blur-2xl" /><img src={NEW_GENESIS_COVER} alt="New Genesis cover" className="relative h-72 w-72 rounded-lg object-cover shadow-2xl sm:h-80 sm:w-80 md:h-96 md:w-96" /></div></div><div className="order-1 text-center md:order-2 md:text-left"><p className="mb-5 inline-block rounded-full border border-indigo-700 px-4 py-1.5 font-mono text-xs uppercase tracking-[0.2em] text-indigo-300">Debut album · {NEW_GENESIS_META.trackCount} tracks</p><h1 className="mb-3 font-bebas text-[clamp(3rem,10vw,8rem)] leading-none tracking-wide text-indigo-100">NEW GENESIS</h1><p className="mb-8 font-cormorant text-2xl italic text-yellow-400/80">MOSES</p><div className="mb-8 flex flex-wrap justify-center gap-4 text-xs font-mono uppercase tracking-widest text-indigo-400/70 md:justify-start"><span>{NEW_GENESIS_META.trackCount} tracks</span><span className="text-indigo-700">·</span><span>{NEW_GENESIS_META.totalDuration}</span><span className="text-indigo-700">·</span><span>{NEW_GENESIS_META.year}</span></div><div className="flex flex-col justify-center gap-3 sm:flex-row md:justify-start"><Link href={NEW_GENESIS_META.listenPath} className="flex items-center justify-center gap-2 rounded-lg bg-indigo-700 px-6 py-3 font-bebas text-lg tracking-wide text-white transition-colors hover:bg-indigo-600">Listen Now <Music className="h-4 w-4" /></Link><Link href="/checkout?product=new-genesis" className="flex items-center justify-center gap-2 rounded-lg border border-yellow-700/60 px-6 py-3 font-bebas text-lg tracking-wide text-yellow-300 transition-colors hover:border-yellow-400 hover:text-yellow-100">Own It — $10 <ShoppingBag className="h-4 w-4" /></Link></div></div></div></section>

      <section className="border-y border-indigo-900/20 px-4 py-16 sm:py-20"><div className="mx-auto grid max-w-5xl gap-10 md:grid-cols-[0.7fr_1.3fr] md:items-start"><div><p className="font-mono text-xs uppercase tracking-[0.25em] text-yellow-500/70">The story</p><h2 className="mt-4 font-bebas text-5xl tracking-wide text-indigo-100">A BEGINNING, RECORDED.</h2></div><p className="font-cormorant text-2xl leading-relaxed text-indigo-100/85">{story}</p></div></section>

      <section className="px-4 py-16 sm:py-20"><div className="mx-auto max-w-3xl"><div className="mb-8 flex items-end justify-between gap-4"><div><p className="font-mono text-xs uppercase tracking-[0.25em] text-yellow-500/70">Record back</p><h2 className="mt-2 font-bebas text-4xl tracking-wide text-indigo-200">TRACKLIST</h2></div><span className="font-mono text-xs uppercase tracking-widest text-indigo-600">{NEW_GENESIS_META.trackCount} tracks · {NEW_GENESIS_META.totalDuration}</span></div><div className="rounded-lg border border-indigo-900/30 bg-black/20 p-3"><p className="px-3 pb-2 pt-1 font-mono text-[10px] uppercase tracking-[0.24em] text-yellow-500/80">The Five Books</p><div className="space-y-1"><RecordTracks tracks={fiveBooks} /></div><div className="mx-3 my-4 border-t border-indigo-900/30" /><p className="px-3 pb-2 font-mono text-[10px] uppercase tracking-[0.24em] text-indigo-500">The project</p><div className="space-y-1"><RecordTracks tracks={remainingTracks} /></div></div><div className="mt-10 flex flex-col justify-center gap-4 sm:flex-row"><Link href={NEW_GENESIS_META.listenPath} className="inline-flex items-center justify-center gap-2 rounded-lg bg-indigo-700 px-8 py-4 font-bebas text-lg tracking-wide text-white transition-colors hover:bg-indigo-600">Start Listening <ArrowRight className="h-5 w-5" /></Link><Link href="/checkout?product=new-genesis" className="inline-flex items-center justify-center gap-2 rounded-lg border border-yellow-700/50 px-8 py-4 font-bebas text-lg tracking-wide text-yellow-300/80 transition-colors hover:border-yellow-500 hover:text-yellow-200">Own It — $10 <ShoppingBag className="h-5 w-5" /></Link></div></div></section>

      <section className="border-y border-indigo-900/20 px-4 py-16 sm:py-20"><div className="mx-auto grid max-w-5xl gap-10 md:grid-cols-2"><div><p className="font-mono text-xs uppercase tracking-[0.25em] text-yellow-500/70">Credits</p><p className="mt-4 text-sm leading-7 text-indigo-100/80">Written and performed by Moses. Recorded at Mount Pisgah Baptist Church, Chicago.<br /><br />Production: Alexis Mendez (ae beats) — Genesis, Exodus, Leviticus, Numbers, Deuteronomy · Bhad S — Suburban Picasso · flavrboy — Angels · ODDstatus — Rock With Me · Additional production: Lucas Quinn, 8een, Eyezeck, Ice!, The Heretic, nomstks.<br /><br />Special thanks to Pastor Robinson of House of Restoration, Pastor Edmond of Second Baptist Church, who baptized Moses, and Pastor Ledbetter of Mount Pisgah Baptist Church.</p></div><div><p className="font-mono text-xs uppercase tracking-[0.25em] text-yellow-500/70">Also on</p><div className="mt-4 space-y-3"><a href="https://mosessog.bandcamp.com/album/new-genesis-2" target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-lg border border-indigo-900/40 px-4 py-3 text-sm text-indigo-200 hover:border-indigo-500"><span>Bandcamp</span><ExternalLink className="h-4 w-4" /></a><a href="https://soundcloud.com/mosessog/sets/new-genesis" target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-lg border border-indigo-900/40 px-4 py-3 text-sm text-indigo-200 hover:border-indigo-500"><span>SoundCloud</span><ExternalLink className="h-4 w-4" /></a><p className="rounded-lg border border-dashed border-indigo-900/40 px-4 py-3 text-xs text-indigo-600">YouTube link coming soon.</p></div></div></div></section>

      <footer className="border-t border-indigo-900/20 px-4 py-10 text-center text-indigo-700"><p className="text-sm">© 2026 MOSES SOG. All rights reserved.</p></footer>
    </main>
  );
}
