import { ArrowLeft, ArrowRight, CircleDollarSign } from 'lucide-react';
import { Link } from 'wouter';
import ProjectVaultCard from '@/components/ProjectVaultCard';
import { PROJECTS } from '@/data/project-catalog';

export default function Store() {
  const [clarity, newGenesis, ...freeProjects] = PROJECTS;

  return (
    <main className="min-h-screen bg-zinc-950 text-zinc-100">
      <section className="border-b border-amber-100/10 bg-[radial-gradient(circle_at_76%_0%,rgba(184,134,11,0.14),transparent_30%),linear-gradient(145deg,#110e0a,#090909)] px-4 py-14 sm:py-20"><div className="mx-auto max-w-7xl"><div className="flex items-center justify-between gap-4 border-b border-amber-100/10 pb-5"><Link href="/" className="inline-flex min-h-11 items-center gap-2 text-[10px] uppercase tracking-[0.18em] text-zinc-400 transition hover:text-amber-200 focus:outline-none focus-visible:ring-2 focus-visible:ring-amber-300"><ArrowLeft className="h-4 w-4" aria-hidden="true" /> Vault</Link><p className="font-display text-lg tracking-[0.18em] text-amber-200">DIRECT STORE</p><Link href="/connect" className="inline-flex min-h-11 items-center gap-2 text-[10px] uppercase tracking-[0.18em] text-zinc-400 transition hover:text-amber-200 focus:outline-none focus-visible:ring-2 focus-visible:ring-amber-300">Connect <ArrowRight className="h-4 w-4" aria-hidden="true" /></Link></div><div className="mt-14 grid gap-8 lg:grid-cols-[0.72fr_1.28fr] lg:items-end"><div><CircleDollarSign className="h-7 w-7 text-amber-200" aria-hidden="true" /><p className="mt-6 text-[10px] uppercase tracking-[0.3em] text-amber-200">Owned music · Direct support</p><h1 className="mt-5 font-display text-7xl leading-[0.78] tracking-[0.1em] text-zinc-50 sm:text-9xl">SUPPORT THE WORK.</h1></div><div><p className="font-serif text-3xl italic leading-tight text-amber-50/85 sm:text-4xl">Direct-to-fan music. No middlemen. Every purchase supports the next recording.</p><p className="mt-5 max-w-2xl text-sm leading-7 text-zinc-400">CLARITY is the flagship digital album. New Genesis welcomes optional support. The rest of the archive remains accessible for free through direct listening and delivery.</p></div></div></div></section>
      <section className="px-4 py-16 sm:py-24"><div className="mx-auto max-w-7xl"><p className="text-[10px] uppercase tracking-[0.28em] text-amber-200">Featured support paths</p><div className="mt-6 grid gap-5 md:grid-cols-2"><ProjectVaultCard project={clarity} featured /><ProjectVaultCard project={newGenesis} /></div><div className="mt-16 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] uppercase tracking-[0.28em] text-zinc-500">Free project downloads</p><h2 className="mt-3 font-display text-5xl tracking-[0.1em] text-zinc-50 sm:text-6xl">THE OPEN ARCHIVE.</h2></div><p className="max-w-md text-sm leading-7 text-zinc-500">Choose a project, listen in its own room, or download the complete ZIP directly.</p></div><div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{freeProjects.map((project) => <ProjectVaultCard key={project.title} project={project} />)}</div></div></section>
    </main>
  );
}
